version: "3"

services:

  app:

    build: .

    depends_on:
 
      -  db

    ports:

      - "5000:5000"

    environment:

      -  FLASK_APP=app.py
     
  db:

    container_name: db

    image: postgres:latest

    env_file: database.conf

    ports:
  
      -  5432:5432

    volumes:
  
      -  vol:/var/lib/postgresql

volumes:
  
  vol:
